"""Slide-deck export for slide_deck=true responses.

Offline .pptx generation via python-pptx so "Export as Deck" works with no
external account. Gamma can swap in behind build_deck() later without touching
app.py — same signature, returns a file path.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from pptx import Presentation
from pptx.util import Inches, Pt

_EXPORT_DIR = Path(__file__).parent / "exports"


def build_deck(response: dict[str, Any], brand: str = "CXO Copilot") -> str:
    """Render a response dict into a .pptx and return its path."""
    _EXPORT_DIR.mkdir(exist_ok=True)
    prs = Presentation()

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = brand + " — Executive Brief"
    slide.placeholders[1].text = "Generated by CXO Copilot"

    # Answer slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Summary"
    slide.placeholders[1].text = response.get("answer", "")

    # Chart slide (rendered as a simple value table)
    chart = response.get("chart") or {}
    if chart.get("type") in ("bar", "line") and chart.get("x"):
        slide = prs.slides.add_slide(prs.slide_layouts[5])
        slide.shapes.title.text = chart.get("title", "Chart")
        x, y = chart["x"], chart["y"]
        rows, cols = len(x) + 1, 2
        tbl = slide.shapes.add_table(
            rows, cols, Inches(1), Inches(1.8), Inches(8), Inches(0.4 * rows)
        ).table
        tbl.cell(0, 0).text, tbl.cell(0, 1).text = "Category", "Value"
        for i, (cat, val) in enumerate(zip(x, y), start=1):
            tbl.cell(i, 0).text = str(cat)
            tbl.cell(i, 1).text = str(val)

    # Sources slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Sources"
    body = slide.placeholders[1].text_frame
    body.text = "Data sources queried:"
    for sid in response.get("sources_used", []):
        p = body.add_paragraph()
        p.text = f"• {sid}"
        p.font.size = Pt(18)

    out = _EXPORT_DIR / "executive_brief.pptx"
    prs.save(out)
    return str(out)
