"""Slide-deck export for slide_deck=true responses.

Offline .pptx generation via python-pptx so "Export as Deck" works with no
external account. Gamma can swap in behind build_deck() later without touching
app.py — same signature, returns a file path.
"""

from __future__ import annotations

import json
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from pptx import Presentation
from pptx.util import Inches, Pt

_EXPORT_DIR = Path(__file__).parent / "exports"
_GAMMA_BASE = "https://public-api.gamma.app/v0.2"


def build_deck(response: dict[str, Any], brand: str = "CXO Copilot") -> str:
    """Render a response dict into a .pptx and return its path."""
    _EXPORT_DIR.mkdir(exist_ok=True)
    prs = Presentation()

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = brand + " — Executive Brief"
    slide.placeholders[1].text = "Generated by CXO Copilot"

    # Answer slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Summary"
    slide.placeholders[1].text = response.get("answer", "")

    # Chart slide (rendered as a simple value table)
    chart = response.get("chart") or {}
    if chart.get("type") in ("bar", "line") and chart.get("x"):
        slide = prs.slides.add_slide(prs.slide_layouts[5])
        slide.shapes.title.text = chart.get("title", "Chart")
        x, y = chart["x"], chart["y"]
        rows, cols = len(x) + 1, 2
        tbl = slide.shapes.add_table(
            rows, cols, Inches(1), Inches(1.8), Inches(8), Inches(0.4 * rows)
        ).table
        tbl.cell(0, 0).text, tbl.cell(0, 1).text = "Category", "Value"
        for i, (cat, val) in enumerate(zip(x, y), start=1):
            tbl.cell(i, 0).text = str(cat)
            tbl.cell(i, 1).text = str(val)

    # Sources slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Sources"
    body = slide.placeholders[1].text_frame
    body.text = "Data sources queried:"
    for sid in response.get("sources_used", []):
        p = body.add_paragraph()
        p.text = f"• {sid}"
        p.font.size = Pt(18)

    out = _EXPORT_DIR / "executive_brief.pptx"
    prs.save(out)
    return str(out)


# ----------------------------------------------------------------- Gamma export
def _gamma_input_text(response: dict[str, Any], brand: str) -> str:
    """Turn a response dict into rich input text for Gamma."""
    lines = [f"# {brand} — Executive Brief", "", response.get("answer", "")]
    chart = response.get("chart") or {}
    if chart.get("type") in ("bar", "line") and chart.get("x"):
        lines += ["", f"## {chart.get('title', 'Key figures')}"]
        for cat, val in zip(chart["x"], chart["y"]):
            lines.append(f"- {cat}: {val}")
    if response.get("sources_used"):
        lines += ["", "## Sources"] + [f"- {s}" for s in response["sources_used"]]
    return "\n".join(lines)


def _gamma_get(path: str, api_key: str) -> dict[str, Any]:
    req = urllib.request.Request(
        f"{_GAMMA_BASE}{path}",
        headers={"X-API-KEY": api_key, "accept": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())


def generate_with_gamma(
    response: dict[str, Any], api_key: str, brand: str = "CXO Copilot",
    poll_timeout: int = 180,
) -> dict[str, Any]:
    """Create a presentation in Gamma from a response. Returns {ok, url|error}.

    Uses the Gamma public Generations API: POST a generation, then poll until
    completed and return the gammaUrl. Needs a Gamma API key (Pro plan).
    """
    body = json.dumps(
        {
            "inputText": _gamma_input_text(response, brand),
            "format": "presentation",
            "textMode": "preserve",
        }
    ).encode()
    req = urllib.request.Request(
        f"{_GAMMA_BASE}/generations",
        data=body,
        method="POST",
        headers={
            "X-API-KEY": api_key,
            "Content-Type": "application/json",
            "accept": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            data = json.loads(r.read())
    except urllib.error.HTTPError as exc:
        return {"ok": False, "error": f"{exc.code} {exc.read().decode(errors='ignore')[:200]}"}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}

    gen_id = data.get("generationId") or data.get("id")
    if not gen_id:
        return {"ok": False, "error": f"no generationId in response: {data}"}

    start = time.time()
    while time.time() - start < poll_timeout:
        time.sleep(5)
        try:
            status = _gamma_get(f"/generations/{gen_id}", api_key)
        except Exception as exc:
            return {"ok": False, "error": f"poll failed: {exc}"}
        state = (status.get("status") or "").lower()
        if state in ("completed", "done", "success"):
            url = status.get("gammaUrl") or status.get("url") or status.get("exportUrl")
            return {"ok": True, "url": url}
        if state in ("failed", "error"):
            return {"ok": False, "error": status.get("message", "Gamma generation failed")}
    return {"ok": False, "error": "Gamma generation timed out — check gamma.app."}
