"""Slide-deck export for slide_deck=true responses.

Offline .pptx generation via python-pptx so "Export as Deck" works with no
external account. Gamma can swap in behind build_deck() later without touching
app.py — same signature, returns a file path.
"""

from __future__ import annotations

import json
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from pptx import Presentation
from pptx.chart.data import CategoryChartData
from pptx.dml.color import RGBColor
from pptx.enum.chart import XL_CHART_TYPE, XL_LEGEND_POSITION
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Inches, Pt

_EXPORT_DIR = Path(__file__).parent / "exports"
_GAMMA_BASE = "https://public-api.gamma.app/v0.2"

# Brand palette
_NAVY = RGBColor(0x11, 0x32, 0x4D)
_BLUE = RGBColor(0x2E, 0x86, 0xC1)
_DARK = RGBColor(0x22, 0x2B, 0x35)
_GREY = RGBColor(0x6B, 0x72, 0x80)
_WHITE = RGBColor(0xFF, 0xFF, 0xFF)


def _blank(prs: "Presentation") -> Any:
    return prs.slides.add_slide(prs.slide_layouts[6])  # truly blank layout


def _rect(slide, left, top, width, height, color) -> None:
    shp = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    shp.fill.solid()
    shp.fill.fore_color.rgb = color
    shp.line.fill.background()
    shp.shadow.inherit = False


def _text(slide, left, top, width, height, text, size, color,
          bold=False, anchor=MSO_ANCHOR.TOP, align=PP_ALIGN.LEFT):
    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.name = "Calibri"
    run.font.color.rgb = color
    return tf


def _header(slide, prs, title) -> None:
    _rect(slide, 0, 0, prs.slide_width, Inches(1.0), _NAVY)
    _rect(slide, 0, Inches(1.0), prs.slide_width, Inches(0.06), _BLUE)
    _text(slide, Inches(0.5), Inches(0.18), prs.slide_width - Inches(1), Inches(0.7),
          title, 26, _WHITE, bold=True, anchor=MSO_ANCHOR.MIDDLE)


def build_deck(response: dict[str, Any], brand: str = "CXO Copilot") -> str:
    """Render a response dict into a styled 16:9 .pptx and return its path."""
    _EXPORT_DIR.mkdir(exist_ok=True)
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    W, H = prs.slide_width, prs.slide_height

    # --- Title slide ---
    s = _blank(prs)
    _rect(s, 0, 0, W, H, _NAVY)
    _rect(s, Inches(0.7), Inches(3.05), Inches(2.2), Inches(0.10), _BLUE)
    _text(s, Inches(0.7), Inches(2.1), W - Inches(1.4), Inches(1.0),
          brand, 44, _WHITE, bold=True)
    _text(s, Inches(0.7), Inches(3.3), W - Inches(1.4), Inches(0.8),
          "Executive Brief", 26, _BLUE, bold=True)
    _text(s, Inches(0.7), Inches(6.7), W - Inches(1.4), Inches(0.5),
          "Generated by CXO Copilot", 12, _GREY)

    # --- Summary slide ---
    s = _blank(prs)
    _header(s, prs, "Summary")
    _text(s, Inches(0.6), Inches(1.4), W - Inches(1.2), H - Inches(2.0),
          response.get("answer", ""), 18, _DARK)

    # --- Chart slide (native rendered chart) ---
    chart = response.get("chart") or {}
    xs, ys = chart.get("x") or [], chart.get("y") or []
    if chart.get("type") in ("bar", "line") and xs and len(xs) == len(ys):
        s = _blank(prs)
        _header(s, prs, chart.get("title", "Key figures"))
        cdata = CategoryChartData()
        cdata.categories = [str(c) for c in xs]
        cdata.add_series("Value", tuple(float(v) for v in ys))
        ctype = XL_CHART_TYPE.LINE_MARKERS if chart["type"] == "line" else XL_CHART_TYPE.COLUMN_CLUSTERED
        gframe = s.shapes.add_chart(
            ctype, Inches(0.6), Inches(1.4), W - Inches(1.2), H - Inches(2.0), cdata
        )
        ch = gframe.chart
        ch.has_legend = False
        try:
            ser = ch.plots[0].series[0]
            ser.format.fill.solid()
            ser.format.fill.fore_color.rgb = _BLUE
        except Exception:
            pass

    # --- Sources slide ---
    s = _blank(prs)
    _header(s, prs, "Data Sources")
    box = s.shapes.add_textbox(Inches(0.6), Inches(1.5), W - Inches(1.2), H - Inches(2.2))
    tf = box.text_frame
    tf.word_wrap = True
    for i, sid in enumerate(response.get("sources_used", []) or ["(none recorded)"]):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        run = p.add_run()
        run.text = f"●  {sid}"
        run.font.size = Pt(20)
        run.font.name = "Calibri"
        run.font.color.rgb = _DARK
        p.space_after = Pt(8)

    out = _EXPORT_DIR / "executive_brief.pptx"
    prs.save(out)
    return str(out)


# ----------------------------------------------------------------- Gamma export
def _gamma_input_text(response: dict[str, Any], brand: str) -> str:
    """Turn a response dict into rich input text for Gamma."""
    lines = [f"# {brand} — Executive Brief", "", response.get("answer", "")]
    chart = response.get("chart") or {}
    if chart.get("type") in ("bar", "line") and chart.get("x"):
        lines += ["", f"## {chart.get('title', 'Key figures')}"]
        for cat, val in zip(chart["x"], chart["y"]):
            lines.append(f"- {cat}: {val}")
    if response.get("sources_used"):
        lines += ["", "## Sources"] + [f"- {s}" for s in response["sources_used"]]
    return "\n".join(lines)


def _gamma_get(path: str, api_key: str) -> dict[str, Any]:
    req = urllib.request.Request(
        f"{_GAMMA_BASE}{path}",
        headers={"X-API-KEY": api_key, "accept": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())


def generate_with_gamma(
    response: dict[str, Any], api_key: str, brand: str = "CXO Copilot",
    poll_timeout: int = 180,
) -> dict[str, Any]:
    """Create a presentation in Gamma from a response. Returns {ok, url|error}.

    Uses the Gamma public Generations API: POST a generation, then poll until
    completed and return the gammaUrl. Needs a Gamma API key (Pro plan).
    """
    body = json.dumps(
        {
            "inputText": _gamma_input_text(response, brand),
            "format": "presentation",
            "textMode": "preserve",
        }
    ).encode()
    req = urllib.request.Request(
        f"{_GAMMA_BASE}/generations",
        data=body,
        method="POST",
        headers={
            "X-API-KEY": api_key,
            "Content-Type": "application/json",
            "accept": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            data = json.loads(r.read())
    except urllib.error.HTTPError as exc:
        return {"ok": False, "error": f"{exc.code} {exc.read().decode(errors='ignore')[:200]}"}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}

    gen_id = data.get("generationId") or data.get("id")
    if not gen_id:
        return {"ok": False, "error": f"no generationId in response: {data}"}

    start = time.time()
    while time.time() - start < poll_timeout:
        time.sleep(5)
        try:
            status = _gamma_get(f"/generations/{gen_id}", api_key)
        except Exception as exc:
            return {"ok": False, "error": f"poll failed: {exc}"}
        state = (status.get("status") or "").lower()
        if state in ("completed", "done", "success"):
            url = status.get("gammaUrl") or status.get("url") or status.get("exportUrl")
            return {"ok": True, "url": url}
        if state in ("failed", "error"):
            return {"ok": False, "error": status.get("message", "Gamma generation failed")}
    return {"ok": False, "error": "Gamma generation timed out — check gamma.app."}
